export const FETCH_PURCHASES_REQUEST    = 'FETCH_PURCHASES_REQUEST';
export const FETCH_PURCHASES_SUCCESS    = 'FETCH_PURCHASES_SUCCESS';
export const FETCH_PURCHASES_FAILURE    = 'FETCH_PURCHASES_FAILURE';

export const REMOVE_PURCHASE_CONFIRM    = 'REMOVE_PURCHASE_CONFIRM';
export const REMOVE_PURCHASE_CANCEL     = 'REMOVE_PURCHASE_CANCEL';
export const REMOVE_PURCHASE_REQUEST    = 'REMOVE_PURCHASE_REQUEST';
export const REMOVE_PURCHASE_SUCCESS    = 'REMOVE_PURCHASE_SUCCESS';
export const REMOVE_PURCHASE_FAILURE    = 'REMOVE_PURCHASE_FAILURE';

export const EDIT_PURCHASE_FIELD_CHANGE = 'EDIT_PURCHASE_FIELD_CHANGE';
export const EDIT_PURCHASE_EXISTING     = 'EDIT_PURCHASE_EXISTING';
export const EDIT_PURCHASE_CANCEL       = 'EDIT_PURCHASE_CANCEL';
export const EDIT_PURCHASE_REQUEST      = 'EDIT_PURCHASE_REQUEST';
export const EDIT_PURCHASE_SUCCESS      = 'EDIT_PURCHASE_SUCCESS';
export const EDIT_PURCHASE_FAILURE      = 'EDIT_PURCHASE_FAILURE';

export const GET_PURCHASE_BY_ID_REQUEST = 'GET_PURCHASE_BY_ID_REQUEST';
export const GET_PURCHASE_BY_ID_SUCCSES = 'GET_PURCHASE_BY_ID_SUCCSES';
export const GET_PURCHASE_BY_ID_FAILURE = 'GET_PURCHASE_BY_ID_FAILURE';
export const GET_PURCHASE_BY_ID_CANCEL = ' GET_PURCHASE_BY_ID_CANCEL';
export const HIDE_DESCRIPTION = 'HIDE_DESCRIPTION';